# Use Node.js LTS
FROM node:20.11.0

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY . .

# Expose Vite's default port
EXPOSE 5173

# Run Vite development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]