version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - db_data:/var/lib/mysql

  be:
    build:
      context: ./backend
    depends_on:
      -  db
    ports:
      - 8080:8080
    environment:
      - REACT_URL= http://localhost:5173
      - JWT_KEY = thitnguoixoi
      - NODE_ENV = development
      - JWT_KEY = thitnguoixoi

  # fe:
  #   build: ./frontend
  #   ports:
  #     - 5173:5173
volumes:
  db_data: