FROM node:20.11.0

WORKDIR /app

# Install bash + dos2unix
RUN apt-get update && apt-get install -y bash dos2unix

# Copy and convert entrypoint.sh first
COPY entrypoint.sh /app/entrypoint.sh
RUN dos2unix /app/entrypoint.sh && chmod +x /app/entrypoint.sh

# Then copy the rest
COPY package*.json ./
RUN npm install
COPY . .

EXPOSE 8080

ENTRYPOINT ["/app/entrypoint.sh"]
